//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentInformationSystemEntities : DbContext
    {
        public StudentInformationSystemEntities()
            : base("name=StudentInformationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<AssignmentScore> AssignmentScores { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<NotificationPreference> NotificationPreferences { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
